name: Run SQL

on:
  push:
    paths:
      - test1.sql

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MySQL client
      run: sudo apt-get install -y mysql-client

    - name: Run SQL script
      env:
        MYSQL_HOST: mysql-rfam-public.ebi.ac.uk
        MYSQL_USER: rfamro
        MYSQL_PORT: 4497
        MYSQL_DB: Rfam
      run: |
        echo "Выполнение SQL-скрипта..."
        mysql --host=$MYSQL_HOST --user=$MYSQL_USER --port=$MYSQL_PORT --database=$MYSQL_DB < test1.sql > ~./my_project/sql_log.txt 2>&1
